






















import tweepy
import csv
import pandas as pd
####input your credentials here

consumer_key = 'aRLGzK3P3MWSz368Hwrn9KIP3'
consumer_secret = 'D5gWYq06j6C6M3Z0uHC54gMK3Ox6jxTxw3RpW2JaUrxmf6CxpH'
access_token = '766383287996645376-KMvy3Nug57h2upYAfm6z8DHvI5ZUSr6'
access_token_secret = 'PoX9jeJmQkjvANW11wgySY6ad1GgFXBqBSn0XL2jJiBww'

# For plotting and visualization:
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
#%matplotlib inline


# API's setup:

#def twitter_setup():
    # Authentication and access using keys:
#    auth.set_access_token(access_token, access_token_secret)
 #   api = tweepy.API(auth,wait_on_rate_limit=True)
    # Return API with authentication:
  #  api = tweepy.API(auth)
   # return api


#ALLE USER
liste = [
'DeisterEdith',
'legemecum',
'ElisAndersz',
'schulle60',
'Fluesterwitz',
'ZeilerOli',
'UweWolff966',
'Horst1941',
'MyCodeOfConduct',
'daspunkt',
'blacklabel_76',
'B_Saft',
'MaulwurfenInfoD',
'LebenMTL',
'Neomammalia',
'chudaske',
'unzensuriert',
'GermanysHero',
'moinmoinsager',
'Ernst1953Do',
'Vilstal',
'Mayday18568706',
'Nichtkonformist',
'LangeHeiko',
'83Schildi',
'Hotte1950',
'propagare',
'Alt_Reichght',
'FridolinPSP',
'JBotanica',
'FloMatthias',
'firstrodewitzer',
'peter_honig',
'derMylius',
'FForstmaier',
'Peter_Nater',
'Resistance_D_H',
'Gothdad',
'GSiebeke',
'SimonNatal',
'nabucco56',
'conflictman_666',
'Pegasusfeder',
'Bigreiner',
'altern_inform',
'ChelseaEF11',
'Hausfrau4ever',
'Libelle2000R',
'rstrohmi',
'traumdiebe',
'hausneubau',
'ha_zett',
'M_N_Herrmann',
'piratenpower999',
'PIONICeer',
'NewRheinberger',
'__a_f_w__',
'KurtKladder',
'IvicDarko',
'titanvacht',
'BeluboxDebria',
'jklhiu',
'Preiset_Kek',
'Eselyx',
'mrstone0856',
'FOSSpatents',
'gunnar_richert',
'FreierAnon',
'Heinrich_Krug',
'choolie211',
'Shekelchen',
'Schuetze_Arsch',
'xandyfit',
'KirchedhH',
'Almoehy',
'PreussischBlau9',
'Marcus_Kaan88',
'clydevpg',
'C4PEC0D',
'WilhelmusJanus',
'danny23032000',
'pseudros',
'machtjanix23',
'neoM1913',
'_ichnicht',
'ichhabwut',
'AfD_OF_Land',
'Reconquista2017',
'Rita_Sauser',
'Obrigkeit1',
'EmiliaC32',
'zugeras',
'sascha_lotz',
'JA_Deutschland',
'Hermann3004',
'Dauerquerulant',
'VolksWahrsager',
'stevvid',
'FHO_Sierra6Lima',
'Arrtrad',
'KerstinMilller',
'astrowolf',
'WeCon14',
'FwOberhausen',
'ohboulderer',
'gagaberlin',
'Lukas64F',
'bananistanerin',
'rigo_troy',
'TravelBonn',
'Filarete14',
'Medienluegen',
'T0MLightyear',
'Asylnachrichten',
'ManniCoke',
'mikoka666',
'Rotpille',
'Politkritiker',
'SprechenUnsNoch',
'KrabatKabat',
'kwogerman7',
'Zeruyu',
'zentrumspartei',
'HeimattreueNdd',
'67muellerPeter',
'Aletheia156',
'Pro_PEGIDA_',
'Jan_Deichmohle',
'LibertasKleinod',
'FactualLiberal',
'offbeat24',
'PhilPerlmutter',
'GoettscheChr',
'4Sonicc',
'FroehlichKaiT',
'Walter29340877',
'norbert55968075',
'BuergerLey',
'JotDora',
'kosgalwies',
'hotnakedlove',
'OriginalRadi',
'RubenSpruck',
'Unlty1',
'Migrantoman',
'Frieda_Tweety',
'FrDnkr',
'PaulePhanter',
'SchreibedenText',
'Korifej1',
'NiemieckaPolity',
'suisgeneris99',
'Nicht_M_',
'GedankenKEK',
'agent_anny007',
'LenaSakuraBlume',
'FlowKoR',
'godsoflazy',
'recon_quista',
'AncapDude',
'Da_Digge',
'Margit11',
'andreas77761',
'SireenAnimaSola',
'dabbelu',
'medec_29',
'Mister_Ka',
'FarSight3',
'_macmike',
'MarkusFieber',
'VictoriaFerna71',
'Reichsvikar',
'Funny1963',
'stoph_w',
'ChicSancho',
'Boehmerschwanz',
'baerchi08',
'ha_schwa',
'AlexBfromG',
'Andreas62582094',
'CapYossarian',
'carlclausewitz1',
'igor_brain',
'Marcel02935041',
'Norbert_1969',
'bienchen6969',
'1zu1_Gedanken',
'unblogd',
'PegidaHeiko',
'PolitikWelt',
'JA_Bremen',
'StH2810',
'dogga767',
'_Hermeneutik',
'aotto1968_2',
'earlybird2010',
'10DMark',
'kochbar1',
'willnurschreibn',
'FreiheitHofer',
'ramsesleben',
'140ZeichenBlog',
'MXLola5',
'charliealpha5',
'_MASKULIST',
'Kontrastfarbe',
'quovadisschland',
'sohnes1',
'Millerntor1',
'stefananderl',
'salzmanufaktur',
'meine_Stimme',
'Islamkritik_',
'HerkunftBRD',
'frankdrebin247',
'Aufzeigen2015',
'Haie_Westhus',
'd1g1tal_nomad',
'einAnalytiker',
'Elke50870671',
'Harald70199',
'sasbrau',
'__himmel___',
'JamoCum',
'beamller1',
'Eddie_1412',
'oberguru55',
'_Denk__Mal_',
'Gomander2',
'paul_kleiber',
'Catweazle123',
'Kolja_Bonke',
'strangelove666',
'Alfiher',
'Gerechtigkeit01',
'PunishersKill',
'HaraldPetermann',
'm4nuPRT',
'JoergRMayer',
'fritzmichel',
'Null_Euro',
'Scotchi77',
'ichsageseinfach',
'NostraTuring',
'reissmann',
'kardasiapat',
'BenFuror',
'1Feedom',
'Freiwilligfrei',
'meischer',
'tino_taffanek',
'kekistan_proud',
'mariae_gloria',
'Deutschland77',
'Anonym2019',
'dampfhanss',
'ZipPi_lalala',
'Kiss_me_Kiara',
'DerVaterlaender',
'AnnaBe5555',
'KatinkaTheis',
'Netztagebuch',
'Nordseegermane',
'bicyclo222octan',
'Dunkeldenk',
'fladdermues',
'Guggulu',
'mathematikos',
'bestbettercheck',
'DudeTheAbide',
'HausiPanam',
'C001D00D',
'AfD_Muenster',
'uwebecher',
'thomaslauer10',
'DJUHMHA',
'Juergen_Fritz',
'andixy9',
'Caro22one',
'exactlyobserved',
'Hrafnel',
'dkdenz',
'tomkoehler252',
'ManfredHeer',
'ronronin1',
'roger896',
'RHamelth',
'Konstanz_Kritik',
'BalsigerAlex',
'dortmundsrechte',
'BerundoKun',
'chungun88',
'trommler69',
'GreenDevil78',
'DeutscherMiche5',
'stopR2G',
'unbequemes',
'headdowner',
'Artikel_20_GG',
'DerGelbeStrich',
'KritischerTroll',
'Huggy54MG',
'PapillonvA1010',
'Saerdnaya',
'2103markus',
'bvbfollower',
'WIR_UNS',
'myaccount47',
'Wolke7Bewohner',
'HektorFrisch',
'LangeNase',
'jakrevedko',
'GuidoDietel',
'twittonium',
'0seben0',
'gezeitengang',
'MrScopolamin',
'AliceSchmarotze',
'pleitier',
'WernerKulikow',
'handschi2',
'OnTo2000',
'Ch_Bartling',
'CH2CH2CH2CH2CH2',
'letzteliste',
'Oidabazi',
'Rheinfront',
'Volkskorrespdt',
'tabanakelwanze',
'ExZimbi',
'HartwigKnoops',
'MillaKeenan',
'sara_dewe',
'Afd_OSN',
'w203go',
'twitt_Alfred',
'p_fraup_',
'padmodi',
'KlausKontra',
'Mario_Hau_AfD',
'Vegaytarier',
'MarcWallace18',
'NoExtreme87',
'aluhut__Akbar__',
'Aquinate2',
'tulpenbieger',
'McNeuhoff',
'floramargarina',
'von_Ziehten',
'wolfwal',
'HikariGoi',
'Tomte_Tummetot',
'JABVDuesseldorf',
'PittivomDorf',
'_Demokratie',
'Barvariano',
'schaefdogschaef',
'Puretruth678',
'larafla0815',
'flensi1',
'ErikWuensche',
'H_Erzbube',
'MenNeedDogs',
'VietusIL',
'Friedemannschu1',
'HartmannLiane',
'hax_pax_max',
'sushimotos',
'fleurliberte',
'Wundi68',
'PaulLamperd',
'AfDBerlin',
'matt88158',
'LucasHoffmann61',
'Susi_Sorgenvoll',
'rostein45',
'LOLitsmo',
'KrahMax',
'kinderpsych',
'SverigAfD',
'JenomProsty2016',
'0815Lucky0815',
'VoxFriburgensis',
'BlickAchse',
'Johannes135',
'kwisatz_h',
'r00chN',
'Unbequem_hoch_3',
'_Piroska',
'VFF77',
'FrauGattin',
'Hohensyburg',
'_PatMurphy_',
'teite99',
'Yoshihjl',
'An_taeus',
'sarajevo_blues',
'gegnspam',
'Follow_th3',
'Craftergut',
'teleherzog',
'Lauro_Doc',
'247ltd',
'heinemo',
'Querdenker1913',
'_Murphyne',
'Dragonheart0815',
'finis_euro',
'0987677_49',
'peter789_',
'randomname77777',
'ralflmuller',
'MartinStoll11',
'AnoMo70',
'Honk2016',
'Falklandfuchs',
'Ropde_',
'Frannylicious79',
'tunesia70',
'WhoIsInGermany0',
'Ruhr_Poet',
'Rumsucher',
'elysagab',
'Schmitt4711',
'nasanasal',
'Imageberatungen',
'BergerBergerie',
'123Lenchen',
'zentralversand',
'Politologe22',
'Montauk_23',
'Claudia_xy',
'Zora_211212',
'wilcon58',
'145hanne',
'frywynd',
'AfDKreisMK',
'SchattenprinzM',
'AntifaTaunus',
'UnzufriedenerB',
'XAgathon',
'Johann_Hoelzl',
'totul69',
'DjJEM',
'jakobalt',
'FreierWaehler',
'Holgart21',
'SapereAude2020',
'Mangalina123',
'herzog_helga',
'EenBerlina',
'mirko1a',
'pet_skeleton',
'StolzerHoGeSa',
'BeRichtung',
'kreativesH',
'PQimple',
'_hypower',
'tafkab76',
'AntiGender',
'erwputz',
'pinselpoetin',
'wolfi232',
'UseDual',
'GuteWolf',
'Metallica71Bln',
'brigitte_cy',
'citoyen_lauris',
'absolut_tabu',
'karlheppner',
'panic2001',
'Vivian_aus_HH',
'p_truschka',
'FranzlXXX',
'cyclinginside',
'svnthmn1',
'Chippolev',
'Cleolante',
'reconquista_ger',
'Suesse_Schnitte',
'pharent',
'Fusselbrat',
'bruzzzler1',
'Showmaster551',
'PeterPa34083139',
'Maulkorbpolitik',
'an_aus_ende',
'DirkZett',
'karatal93',
'lou2567',
'napfsuelze',
'DWTwentyTwo',
'NordmannThies',
'Der_Kleckser',
'Mut_Buerger1',
'FreieMeinungen',
'_Sakrosankt',
'fahrtwindt',
'PutinTroll2',
'Cock4ndPussy',
'dieter_heil',
'SirMotzALot',
'cdk68',
'KontraKulturell',
'_Rosenkavalier',
'SebastianHertel',
'von_Steiner',
'MaikM80',
'gertwalterwolf',
'cassandralipsia',
'berlinpapers',
'ukw11',
'DetlefBahlke',
'Emerald_Nunchuk',
'hitman075',
'PaulSch72969276',
'uwe2601',
'senormayer21',
'Vallisblog',
'SM100d',
'GiselaHaaase',
'Beams_Game',
'abetselina',
'Nobby1949Z',
'ZukunftCH',
'Rilana41',
'bmuonline',
'OehzenMiriam',
'WeiseMeta',
'donlwl',
'dropeaves',
'KolibriRosado',
'words4free',
'JDornSXM',
'ban_phonsung',
'Feliciani84',
'Thor_Umar_Alman',
'HHOldboy',
'doppel500',
'politironie',
'Gesinnungslaerm',
'poschuetzge',
'AndreasTT',
'PeterMahler5',
'ziemlich_stark',
'AfdMatzke',
'lausitzman',
'REtzlstorfer',
'DidiFreiheit',
'DirkderKaiser',
'HelenaDeZeus',
'draxkrieger',
'DerPatriotDE',
'maxklartext',
'Rudisagmal',
'tess_mc_kay',
'BilBuHa_iR',
'kaiserwetter49',
'Supadicdic',
'uwe_kamann',
'Bchner2',
'udo_greuel',
'Nastasssja',
'michistelle',
'raggna111',
'HomeboyHeinrich',
'Ann__Kelly',
'nittom',
'PackWelcome',
'nipnups',
'athanaric13',
'GGosebrecht',
'Deutschlaender1',
'marcboe',
'NSOberberg',
'GefrKamnitzer',
'schalomi',
'AiSardegna',
'Europa_Nostra',
'Swingtanz',
'thomas1969er',
'mai_thai77',
'BukowskisNephew',
'trueffel22',
'elbewelle',
'Bund4ever',
'Jiggy187',
'LukefromGer',
'AfDLichtenberg',
'sabine_m_b',
'CDonclaus',
'MarcBruenjesDE',
'Wahlplakate2016',
'ennof_',
'Frauenpanorama',
'P_Sonnenanbeter',
'Hans_J_Peter',
'Wedelprinz',
'KlausDFrank',
'Lechfeld955',
'h_aus_koeln',
'gergrubi',
'timtom0815',
'klausmeier0104',
'rantanplan1412',
'kekistani1',
'evelix26',
'hessenbursche',
'artepmobil',
'JuttaMBrandt',
'geli9001',
'C_Sidorow',
'godefroy99',
'Gekko125',
'WeLoveHaram',
'fragichmich',
'Oedoen1523AD',
'leaks_nsu',
'Segeltexter',
'Gabelzaehler',
'this_one_world',
'Luicifer6',
'verusoss1',
'herr_helmut',
'nunu_balloon',
'WalkofLife66',
'Dieter_Stein',
'derKongoMueller',
'lossorg',
'winston_groovy',
'neander777',
'ThomasVerheugen',
'Koppschuettla',
'hohlraumsausen',
'Cimbasi',
'Steuerzahler01',
'anrefi',
'Sk4nd41',
'hetzpetz',
'Udai23517958',
'OKnauer',
'M_T_Franz',
'DieBajuwaren',
'demokratiedoc',
'freddynasevoll',
'Newsboy1899',
'Leopoldinjo',
'LSteinwandter',
'vzuschauer',
'lawracks',
'Khalidafan',
'Yorck_',
'knaagi',
'Andy_Sch16',
'FreiesNetz88',
'AndrewRoussak',
'2018_AfDwaehlen',
'Dieaak',
'ainyrockstar',
'fernetpunker',
'krainde',
'Rockopornero',
'Kybeline',
'HermannMaier23',
'mywordsrmessage',
'schottenhaml',
'wutkopf',
'leopoldnikon',
'ArchangelBlue58',
'heutesnow',
'laurin15320',
'OppressedFart',
'DirkHafermann',
'katorin_jou',
'noherrmann',
'Msteinlin',
'waszumelden',
'wendt_joachim',
'gegenUmvolkung',
'peppermind',
'Zaretten',
'VPfafenrot',
'Matzomaniak',
'euroztar',
'twittschler',
'Leo27027232',
'_deus_lo_vult',
'tschrammen',
'Epithelgewebe',
'DirtyHarry112',
'DerLiuhvan',
'SoBitte',
'BarbaraKube',
'waldruhe',
'rwschmidt1',
'Twente_Chris',
'SarraKowsky',
'strandreiter',
'Ralf41996825',
'FreavonWegen',
'RiRotb',
'dima973',
'WolfHansen',
'ossi1232',
'Mo190311',
'FriedrichsErbe',
'KoppReport',
'Schwaebli1',
'Folienschnitzer',
'gellis18',
'nveritatis',
'JuliaMertensJM',
'NOONENOTHINGNO',
'Der_Aufbruch',
'Ich2ES',
'mic_eff',
'Franz_Ohse',
'krokotasche',
'DeplorableJp',
'HagenSon_71',
'DMittelhesse',
'MattFK',
'bruchhof66',
'Anne_Zielisch',
'dadeldi',
'fepBWm',
'FreeWorldOne',
'jato122',
'eckicgn',
'Verriss',
'kuechenbulle72',
'schlusselszene',
'PaulSchneider72',
'LucaHuerlimann',
'Regenbeobachter',
'White_Haven',
'xEasyx',
'maxfcbayern1996',
'eurogegner',
'ManfredBuder',
'BestBidderGi',
'DrThomasBruns',
'Liesenfleger',
'Thueringen_',
'CHiillaH69',
'GmaGuenter',
'UweSchulz4',
'Boeses_Schaf',
'merdeux_',
'IllyrioM',
'Jacobus_Liftus',
'Der_Berzel',
'KarlSchneider1',
'WhiteStarMM',
'Deisterlinchen1',
'jayne_wohn',
'horstgertler1',
'Kaffee_Racer',
'MagenheimE',
'PetraMable',
'peterroger17',
'AB_National',
'impressivaMicha',
'gordon_deitrich',
'kommentator1234',
'Identitaere_B',
'OneStepBayond',
'dtpmaker',
'Ey_Jackson',
'Jack_Ewiehose',
'timonisch',
'tantegerd1',
'AlteElster',
'Torti_N',
'RuhrpottEule',
'Junta2Puschkin',
'AfD_Paderborn',
'Berapaula1960',
'KlausSchaper',
'dimetrodon109',
'46616C7365',
'mortalhope1',
'myFavoriteKraut']


auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
extractor = tweepy.API(auth,wait_on_rate_limit = True)


#for dudes in liste:
#    print(dudes)
#    test = extractor.lookup_users(screen_names=liste)
#    print(test)

#print("LENGTH:")
#print(len(test))

#data2 = pd.DataFrame(columns=['Tweets', 'len', 'ID', 'Date', 'Source', 'Likes', 'RT'])
#df = pd.DataFrame({'A' : [np.nan]})

#liste2 = ['user:']

# Open/create a file to append data to
csvFile = open('result.csv', 'a')

#Use csv writer
csvWriter = csv.writer(csvFile)


# pro_trump=['TruthSerum888','karlyherron', 'R41nB14ck', 'RedApplePol', 'MKhaoS_86']
for screen_name in liste:
    try:
        user_followers = extractor.friends_ids(id=screen_name)# this returns the interger value of the user id a sepcifc user is following

    except tweepy.TweepError as t:
        if t.api_code == 50: # The code corresponding to the user not found error
            print("screen_name that failed=",  screen_name)
            liste.remove(screen_name)
            #print(liste)
        elif t.api_code == 88: # The code for the rate limit error
            #time.sleep(15*60) # Sleep for 15 minutes
            print("rate limit")
    else:# if no error
         #print("No error ", screen_name)
         #liste2.append(screen_name)
        print(screen_name)
        csvWriter.writerow("'" + screen_name  + "',")

csvFile.close()

